version: "3"
services:
  backend:
    container_name: rails_grpc_demo_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_HOST: "db"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD:
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/var/www/app
      - rails_grpc_demo_backend_bundle_volume:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    networks:
      - rails_grpc_demo_network
  redis:
    container_name: rails_grpc_demo_redis
    image: redis:6.2.7-alpine
    expose:
      - 6379
    volumes:
      - rails_grpc_demo_redis_volume:/data
    networks:
      - rails_grpc_demo_network
  db:
    container_name: rails_grpc_demo_db
    image: mysql:8.0.33
    command: >
      mysqld
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - rails_grpc_demo_db_volume:/var/lib/mysql
    networks:
      - rails_grpc_demo_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  rails_grpc_demo_backend_bundle_volume:
  rails_grpc_demo_db_volume:
  rails_grpc_demo_redis_volume:
networks:
  rails_grpc_demo_network:
